-- MySQL Script generated by MySQL Workbench
-- Thu Sep 13 22:36:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema securitygame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema securitygame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `securitygame` DEFAULT CHARACTER SET utf8 ;
USE `securitygame` ;

-- -----------------------------------------------------
-- Table `securitygame`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securitygame`.`games` (
  `id` INT NOT NULL,
  `user` VARCHAR(30) NOT NULL,
  `score` INT,
  `time` time,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `securitygame`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `securitygame`.`answers` (
  `f_game_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `answer` INT default 0,
  PRIMARY KEY (`f_game_id`, `question_id`),
  INDEX `fk_games_answers_idx` (`f_game_id` ASC),
  CONSTRAINT `fk_games_answers1`
    FOREIGN KEY (`f_game_id`)
    REFERENCES `securitygame`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- View `securitygame`.`view_player_data`
-- -----------------------------------------------------
CREATE VIEW view_player_data AS 
SELECT MAX(id) AS totalPlayers,
  ((SELECT COUNT(id)
    FROM securitygame.games
    WHERE time > 0) / MAX(id)) AS finishedPercent 
FROM securitygame.games;

-- -----------------------------------------------------
-- View `securitygame`.`view_correct_answers_per_question`
-- View `securitygame`.`view_false_answers_per_question`
-- View `securitygame`.`view_no_answer_given_per_question`
-- View `securitygame`.`view_question_data`
-- -----------------------------------------------------
CREATE VIEW view_correct_answers_per_question AS
  SELECT question_id, COUNT(answer) AS correctAnswers
  FROM securitygame.answers
  WHERE answer = 1
  GROUP BY question_id;

CREATE VIEW view_false_answers_per_question AS
  SELECT question_id, COUNT(answer) AS falseAnswers
  FROM securitygame.answers
  WHERE answer = 2
  GROUP BY question_id;

CREATE VIEW view_no_answer_given_per_question AS
  SELECT question_id, COUNT(answer) AS noAnswer
  FROM securitygame.answers
  WHERE answer = 0
  GROUP BY question_id;

CREATE VIEW view_question_data AS
  SELECT c.question_id AS id,
	(c.correctAnswers+f.falseAnswers+n.noAnswer) AS totalAnswers,
  c.correctAnswers,
  (c.correctAnswers / (c.correctAnswers+f.falseAnswers+n.noAnswer)) AS correctPercent,
  f.falseAnswers,
  (f.falseAnswers / (c.correctAnswers+f.falseAnswers+n.noAnswer)) AS falsePercent,
  n.noAnswer,
  (n.noAnswer / (c.correctAnswers+f.falseAnswers+n.noAnswer)) AS noAnswerPercent
  FROM securitygame.view_correct_answers_per_question AS c
  JOIN securitygame.view_false_answers_per_question AS f
  ON c.question_id = f.question_id
  JOIN securitygame.view_no_answer_given_per_question AS n
  ON f.question_id = n.question_id;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Add guest user
-- -----------------------------------------------------
GRANT select, insert, update, delete
  ON securitygame.*
  TO guest@localhost
  IDENTIFIED BY "Super-Safes-Passwort123";